[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "pythontutor"
version = "0.1.0"
authors = [
  { name = "Krystian Nmeze", email = "krystianmaccs@gmail.com" },
]
description = "An interactive Python learning shell with lessons and projects"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: Unix",
  "License :: OSI Approved :: MIT License",
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
  "requests>=2.28.0",  # For GitHub API integration
]

[project.urls]
Homepage = "https://github.com/sauron136/pythontutor"
Issues = "https://github.com/sauron136/pythontutor/issues"

[project.scripts]
pythontutor = "python_tutor.tutor:main"

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[tool.hatch.build.targets.wheel]
packages = ["src/python_tutor"]
